runtime: java17
entrypoint: 'java -jar target/employee1-0.0.1-SNAPSHOT.jar'

env_variables:
  SPRING_PROFILES_ACTIVE: cloud

beta_settings:
  cloud_sql_instances: employee1-447012:us-east1:sqldb

readiness_check:
  path: "/_ah/health"
  timeout_sec: 4
  check_interval_sec: 10
  failure_threshold: 3
  success_threshold: 1

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.75

instance_class: F2

handlers:
  - url: /swagger-ui.html
    static_files: public/swagger-ui.html
    upload: public/swagger-ui.html
    http_headers:
      Access-Control-Allow-Origin: '*'
      Access-Control-Allow-Methods: 'GET, POST, PUT, DELETE, OPTIONS'
      Access-Control-Allow-Headers: 'Content-Type, Authorization'
